
spring:
  application:
    name: jtalk
  profiles:
    default: local
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: false
      path: /h2-console


jtalk:
  frontUrl: "http://localhost:8080"
  # Database configuration (h2, oracle, mssql, postgresql, mysql, mariadb)
  database: mysql

  # Oracle database configuration
  datasource:
    oracle:
      driver-class-name: oracle.jdbc.OracleDriver
      url: jdbc:oracle:thin:@localhost:1521:xe
      username: system
      password: password

    # Microsoft SQL Server configuration
    mssql:
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      url: jdbc:sqlserver://localhost:1433;databaseName=jtalk;encrypt=false
      username: sa
      password: password

    # PostgreSQL configuration
    postgresql:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/jtalk
      username: postgres
      password: password

    # MySQL configuration
    mysql:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:13306/jtalk?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      username: root
      password: 890214hf

    # MariaDB configuration
    mariadb:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://localhost:3306/jtalk
      username: root
      password: password